version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
    ports:
    - "5555:5432"
  api:
    depends_on:
      - postgres
    build:
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=password
      - PG_PORT=5432
    ports:
    - "3000:3000"